# Each section from every releasenote are combined when the
# CHANGELOG.rst is rendered. So the text needs to be worded so that
# it does not depend on any information only available in another
# section. This may mean repeating some details, but each section
# must be readable independently of the other.
#
# Each section note must be formatted as reStructuredText.
---
upgrade:
  - |
    Update systemd configuration. Before if `unit_names` and `unit_regexes`
    are not set, all units are monitored. Now `unit_names` is required and only
    matching units will be monitored, `unit_regexes` have been removed (avoid
    accidental monitoring of too many metrics).
  - |
    New systemd configuration `private_socket`, and `max_units` have been added.
    Default is now prefixed with `/host` when using Docker Agent.
  - |
    Several systemd metrics have been renamed (the integration is not public
    yet).
